"""Order plan with split lots, a dated deadline and a future release. Time unit: minutes."""

MODEL = {'name': '두 라인의 유연 생산 공장',
 'mode': 'pull',
 'duration': 90,
 'seed': 42,
 'source': {'count': 30, 'interval': 3, 'products': ['A', 'B']},
 'processes': [{'id': 'cut', 'name': '가공'},
               {'id': 'inspect', 'name': '검사'},
               {'id': 'pack', 'name': '포장'}],
 'machines': [{'id': 'CUT_A', 'name': '가공기 A', 'process': 'cut', 'line': 'A', 'time': 7},
              {'id': 'CUT_B', 'name': '가공기 B', 'process': 'cut', 'line': 'B', 'time': 9},
              {'id': 'QC_A', 'name': '검사기 A', 'process': 'inspect', 'line': 'A', 'time': 6},
              {'id': 'QC_B', 'name': '검사기 B', 'process': 'inspect', 'line': 'B', 'time': 8},
              {'id': 'PACK_A', 'name': '포장기 A', 'process': 'pack', 'line': 'A', 'time': 5},
              {'id': 'PACK_B', 'name': '포장기 B', 'process': 'pack', 'line': 'B', 'time': 5}],
 'routes': [{'id': 'r1',
             'from': 'INPUT',
             'to': 'CUT_A',
             'priority': 0,
             'delay': 1,
             'product': '*',
             'enabled': True},
            {'id': 'r2',
             'from': 'INPUT',
             'to': 'CUT_B',
             'priority': 0,
             'delay': 1,
             'product': '*',
             'enabled': True},
            {'id': 'r3',
             'from': 'CUT_A',
             'to': 'QC_A',
             'priority': 0,
             'delay': 1,
             'product': '*',
             'enabled': True},
            {'id': 'r4',
             'from': 'CUT_B',
             'to': 'QC_B',
             'priority': 0,
             'delay': 1,
             'product': '*',
             'enabled': True},
            {'id': 'r5',
             'from': 'CUT_A',
             'to': 'QC_B',
             'priority': 10,
             'delay': 2,
             'product': '*',
             'enabled': True},
            {'id': 'r6',
             'from': 'CUT_B',
             'to': 'QC_A',
             'priority': 10,
             'delay': 2,
             'product': '*',
             'enabled': True},
            {'id': 'r7',
             'from': 'QC_A',
             'to': 'PACK_A',
             'priority': 0,
             'delay': 1,
             'product': '*',
             'enabled': True},
            {'id': 'r8',
             'from': 'QC_B',
             'to': 'PACK_B',
             'priority': 0,
             'delay': 1,
             'product': '*',
             'enabled': True},
            {'id': 'r9',
             'from': 'PACK_A',
             'to': 'OUTPUT',
             'priority': 0,
             'delay': 1,
             'product': '*',
             'enabled': True},
            {'id': 'r10',
             'from': 'PACK_B',
             'to': 'OUTPUT',
             'priority': 0,
             'delay': 1,
             'product': '*',
             'enabled': True}],
 'time_origin': '2026-09-10T09:00:00+09:00',
 'order_risk_window': 15,
 'orders': [{'id': 'URGENT',
             'product': 'A',
             'quantity': 6,
             'release_time': 0,
             'priority': -10,
             'due_date': '2026-09-10T09:25:00+09:00',
             'customer': 'Example customer',
             'reference': 'PO-001',
             'lots': [{'id': 'URGENT_1', 'quantity': 2},
                      {'id': 'URGENT_2', 'quantity': 4, 'release_time': 5}]},
            {'id': 'REGULAR',
             'product': 'B',
             'quantity': 3,
             'release_time': 10,
             'priority': 0,
             'due_time': 60},
            {'id': 'NEXT',
             'product': 'A',
             'quantity': 5,
             'release_time': 120,
             'due_time': 180,
             'priority': 0}]}

def choose_candidate(candidates, context):
    """Business priority and due slack are explicit custom criteria (lower first).

    candidate.priority remains route priority. order contains original order values.
    The default engine chooser does NOT use these business criteria.
    """
    from messages import message
    chosen = min(candidates, key=lambda c: (
        c['lot_priority'], c['due_slack'] if c['due_slack'] is not None else float('inf'),
        c['priority'], c['ready_since'], c['id']))
    return chosen['id'], message('order_dispatch_reason', chosen['lot_priority'],
                                chosen['due_slack'] if chosen['due_slack'] is not None else '—')
